"""create comunidade table

Revision ID: 343eb01d717c
Revises: 
Create Date: 2024-07-18 15:54:01.398155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343eb01d717c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade',
    sa.Column('comunidade_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('comunidade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunidade')
    # ### end Alembic commands ###
