"""create titular e endereco

Revision ID: ad4887817db5
Revises: 708f74c479a1
Create Date: 2024-07-18 16:15:07.383556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4887817db5'
down_revision: Union[str, None] = '343eb01d717c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titular',
    sa.Column('titular_id', sa.String(length=32), nullable=False),
    sa.Column('numero_dizimista', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('cpf', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('comunidade_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['comunidade_id'], ['comunidade.comunidade_id'], ),
    sa.PrimaryKeyConstraint('titular_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('endereco',
    sa.Column('endereco_id', sa.String(length=32), nullable=False),
    sa.Column('titular_id', sa.String(length=32), nullable=True),
    sa.Column('cep', sa.String(length=32), nullable=False),
    sa.Column('rua', sa.String(length=32), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=32), nullable=False),
    sa.Column('cidade', sa.String(length=32), nullable=False),
    sa.Column('complemento', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.titular_id'], ),
    sa.PrimaryKeyConstraint('endereco_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    op.drop_table('titular')
    # ### end Alembic commands ###
