"""create dependente table

Revision ID: dc8968bcd836
Revises: ad4887817db5
Create Date: 2024-07-18 16:58:34.822345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8968bcd836'
down_revision: Union[str, None] = 'ad4887817db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependente',
    sa.Column('dependente_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.Column('sexo', sa.String(length=32), nullable=False),
    sa.Column('titular_id', sa.String(length=32), nullable=True),
    sa.Column('tipo_dependente', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.titular_id'], ),
    sa.PrimaryKeyConstraint('dependente_id')
    )
    op.add_column('titular', sa.Column('sexo', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titular', 'sexo')
    op.drop_table('dependente')
    # ### end Alembic commands ###
