"""add mais campos Payment

Revision ID: 046cabd3610d
Revises: 6f4f10c73a85
Create Date: 2024-10-08 22:18:41.936950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046cabd3610d'
down_revision = '6f4f10c73a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_payment', sa.String(length=32), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id_payment')

    # ### end Alembic commands ###
