"""Altera data de nascimento para somente DATE

Revision ID: 28a5024b8e95
Revises: 046cabd3610d
Create Date: 2024-10-09 21:47:46.249775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a5024b8e95'
down_revision = '046cabd3610d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titular', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titular', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
