"""Atualiza o modelo User

Revision ID: 5247d61dcd8a
Revises: 
Create Date: 2024-09-17 19:26:45.342527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5247d61dcd8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunidade',
    sa.Column('comunidade_id', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comunidade_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('titular',
    sa.Column('titular_id', sa.String(length=32), nullable=False),
    sa.Column('numero_dizimista', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('sexo', sa.String(length=32), nullable=False),
    sa.Column('cpf', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.Column('comunidade_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['comunidade_id'], ['comunidade.comunidade_id'], ),
    sa.PrimaryKeyConstraint('titular_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dependente',
    sa.Column('dependente_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sexo', sa.String(length=32), nullable=False),
    sa.Column('titular_id', sa.String(length=32), nullable=True),
    sa.Column('tipo_dependente', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.titular_id'], ),
    sa.PrimaryKeyConstraint('dependente_id')
    )
    op.create_table('endereco',
    sa.Column('endereco_id', sa.String(length=32), nullable=False),
    sa.Column('titular_id', sa.String(length=32), nullable=True),
    sa.Column('cep', sa.String(length=32), nullable=False),
    sa.Column('rua', sa.String(length=32), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=32), nullable=False),
    sa.Column('cidade', sa.String(length=32), nullable=False),
    sa.Column('complemento', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.titular_id'], ),
    sa.PrimaryKeyConstraint('endereco_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('titular_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.titular_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('endereco')
    op.drop_table('dependente')
    op.drop_table('titular')
    op.drop_table('users')
    op.drop_table('comunidade')
    # ### end Alembic commands ###
